name: Build Firmware

on: workflow_dispatch

permissions:
  contents: read

jobs:
  build:
    runs-on: ubuntu-24.04

    steps:
    - name: Checkout repository
      uses: actions/checkout@v7
      with:
        submodules: true

    - name: Install Toolchain
      run: make install-toolchain

    - name: Build
      run: make

    - name: Upload Build Artifact
      uses: actions/upload-artifact@v7
      with:
        path: build/*.bin
        if-no-files-found: error
        archive: false
